-- print output in columns
.mode column

-- enforce foreign key constraints
PRAGMA foreign_keys = True;

CREATE TABLE Dinosaur(
dinoID varchar(10) NOT NULL,
dinoName varchar(255) NOT NULL,
length float(6,2) NOT NULL,
diet varchar(255) NOT NULL,
period varchar(10) NOT NULL,

  PRIMARY KEY (dinoID)
);

-- The following may be added to the CREATE statement
-- Primary Key Syntax (added after field name and NOT NULL)
--     
--          or for compound PK
--     CONSTRAINT PK_compoundFieldName PRIMARY KEY (field1,field2)
-- Foreign Key Syntax (added after field list)
--     FOREIGN KEY (field name) REFERENCES tableName(fieldName)
-- Boolean Field Type
--     For some SQL environments 'bool' may have to be changed to 'int'
-- Text Field Max Size
--     Edit (255) to required length
-- Validation of length of text (added after create statement as new statement
--     CHECK (CHAR_LENGTH(fieldName) > value)
-- Range Check (added after field list)
--     CHECK (fieldName >= value)
--     CHECK (fieldName >= value AND fieldName <= value2)
-- Restricted choice
--     CHECK(fieldName in ('value1','value2','value3')) 

CREATE TABLE Fossil(
fossilID int NOT NULL,
countryFound varchar(25) NOT NULL,
year int NOT NULL,
person varchar(100) NOT NULL,
dinoID varchar(10) NOT NULL,

  PRIMARY KEY (fossilID),
  FOREIGN KEY (dinoID) REFERENCES Dinosaur(dinoID)
);

-- The following may be added to the CREATE statement
-- Primary Key Syntax (added after field name and NOT NULL)
--     PRIMARY KEY (fieldName)
--          or for compound PK
--     CONSTRAINT PK_compoundFieldName PRIMARY KEY (field1,field2)
-- Foreign Key Syntax (added after field list)
--     FOREIGN KEY (field name) REFERENCES tableName(fieldName)
-- Boolean Field Type
--     For some SQL environments 'bool' may have to be changed to 'int'
-- Text Field Max Size
--     Edit (255) to required length
-- Validation of length of text (added after create statement as new statement
--     CHECK (CHAR_LENGTH(fieldName) > value)
-- Range Check (added after field list)
--     CHECK (fieldName >= value)
--     CHECK (fieldName >= value AND fieldName <= value2)
-- Restricted choice
--     CHECK(fieldName in ('value1','value2','value3')) 

INSERT INTO Dinosaur VALUES('DINO_01','Aardonyx',0.8,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_02','Abelisaurus',9,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_03','Achelousaurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_04','Achillobator',5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_05','Acrocanthosaurus',12,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_06','Aegyptosaurus',15,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_07','Afrovenator',9,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_08','Agilisaurus',1.5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_09','Alamosaurus',21,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_10','Albertaceratops',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_100','Erketu',15,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_101','Erlikosaurus',3.4,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_102','Euhelopus',10,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_103','Euoplocephalus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_104','Europasaurus',6.2,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_105','Eustreptospondylus',7,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_106','Fukuiraptor',4.2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_107','Fukuisaurus',4.7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_108','Gallimimus',6,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_109','Gargoyleosaurus',4,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_11','Albertosaurus',9,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_110','Garudimimus',4.7,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_111','Gasosaurus',4,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_112','Gasparinisaura',0.8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_113','Gastonia',4.6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_114','Giganotosaurus',12.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_115','Gilmoreosaurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_116','Giraffatitan',23,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_117','Gobisaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_118','Gorgosaurus',8.6,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_119','Goyocephale',2,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_12','Alectrosaurus',5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_120','Graciliceratops',2,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_121','Gryposaurus',10,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_122','Guaibasaurus',1.8,'Herbivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_123','Guanlong',3,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_124','Hadrosaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_125','Hagryphus',3,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_126','Haplocanthosaurus',21.5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_127','Harpymimus',2,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_128','Herrerasaurus',3,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_129','Hesperosaurus',6,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_13','Alioramus',6,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_130','Heterodontosaurus',1.2,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_131','Heyuannia',2,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_132','Homalocephale',1.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_133','Huayangosaurus',4.5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_134','Hylaeosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_135','Hypacrosaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_136','Hypsilophodon',2.3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_137','Iguanodon',10,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_138','Indosuchus',7,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_139','Irritator',6.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_14','Allosaurus',12,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_140','Isisaurus',18,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_141','Janenschia',20,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_142','Jaxartosaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_143','Jingshanosaurus',5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_144','Jinzhousaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_145','Jobaria',21,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_146','Juravenator',0.8,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_147','Kentrosaurus',5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_148','Khaan',1.8,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_149','Kotasaurus',9,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_15','Alvarezsaurus',2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_150','Kritosaurus',8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_151','Lambeosaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_152','Lapparentosaurus',15,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_153','Leaellynasaura',2,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_154','Leptoceratops',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_155','Lesothosaurus',1,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_156','Liaoceratops',0.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_157','Ligabuesaurus',24,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_158','Liliensternus',5,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_159','Lophorhothon',4.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_16','Amargasaurus',12,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_160','Lophostropheus',6.2,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_161','Lufengosaurus',6,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_162','Lurdusaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_163','Lycorhinus',1.2,'Herbivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_164','Magyarosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_165','Maiasaura',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_166','Majungasaurus',6,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_167','Malawisaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_168','Mamenchisaurus',22,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_169','Mapusaurus',13,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_17','Ammosaurus',5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_170','Marshosaurus',6,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_171','Masiakasaurus',2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_172','Massospondylus',4,'Omnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_173','Maxakalisaurus',13,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_174','Megalosaurus',9,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_175','Melanorosaurus',12,'Omnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_176','Metriacanthosaurus',8.2,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_177','Microceratus',0.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_178','Micropachycephalosaurus',0.6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_179','Microraptor',0.8,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_18','Ampelosaurus',15,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_180','Minmi',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_181','Monolophosaurus',5.7,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_182','Mononykus',1,'Unknown','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_183','Mussaurus',3,'Herbivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_184','Muttaburrasaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_185','Nanshiungosaurus',4.4,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_186','Nedoceratops',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_187','Nemegtosaurus',13,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_188','Neovenator',7.4,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_189','Neuquenosaurus',10,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_19','Amygdalodon',15,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_190','Nigersaurus',15,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_191','Nipponosaurus',4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_192','Noasaurus',1,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_193','Nodosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_194','Nomingia',1.6,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_195','Nothronychus',5.3,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_196','Nqwebasaurus',1,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_197','Omeisaurus',20,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_198','Opisthocoelicaudia',12,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_199','Ornitholestes',2,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_20','Anchiceratops',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_200','Ornithomimus',4,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_201','Orodromeus',2,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_202','Oryctodromeus',2.1,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_203','Othnielia',1.4,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_204','Ouranosaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_205','Oviraptor',2,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_206','Pachycephalosaurus',8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_207','Pachyrhinosaurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_208','Panoplosaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_209','Pantydraco',3,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_21','Anchisaurus',2,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_210','Paralititan',28,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_211','Parasaurolophus',11,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_212','Parksosaurus',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_213','Patagosaurus',18,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_214','Pelicanimimus',2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_215','Pelorosaurus',25,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_216','Pentaceratops',6.8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_217','Piatnitzkysaurus',4.2,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_218','Pinacosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_219','Plateosaurus',7,'Herbivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_22','Ankylosaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_220','Podokesaurus',0.9,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_221','Poekilopleuron',9,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_222','Polacanthus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_223','Prenocephale',2.4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_224','Probactrosaurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_225','Proceratosaurus',4.1,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_226','Procompsognathus',1,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_227','Prosaurolophus',7.6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_228','Protarchaeopteryx',2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_229','Protoceratops',1.8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_23','Anserimimus',3.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_230','Protohadros',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_231','Psittacosaurus',2,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_232','Quaesitosaurus',23,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_233','Rebbachisaurus',20,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_234','Rhabdodon',4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_235','Rhoetosaurus',15,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_236','Rinchenia',2.5,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_237','Riojasaurus',5.2,'Herbivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_238','Rugops',7,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_239','Saichania',6.6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_24','Antarctosaurus',18,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_240','Saltasaurus',12,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_241','Saltopus',1,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_242','Sarcosaurus',3,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_243','Saurolophus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_244','Sauropelta',6.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_245','Saurophaganax',12,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_246','Saurornithoides',3,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_247','Scelidosaurus',4,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_248','Scutellosaurus',1.2,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_249','Secernosaurus',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_25','Apatosaurus',21,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_250','Segisaurus',1.5,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_251','Segnosaurus',4,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_252','Shamosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_253','Shanag',0.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_254','Shantungosaurus',15,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_255','Shunosaurus',10,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_256','Shuvuuia',0.6,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_257','Silvisaurus',4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_258','Sinocalliopteryx',2.4,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_259','Sinornithosaurus',2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_26','Aragosaurus',18,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_260','Sinosauropteryx',1,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_261','Sinovenator',1,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_262','Sinraptor',7.6,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_263','Sonidosaurus',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_264','Spinosaurus',18,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_265','Staurikosaurus',2,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_266','Stegoceras',2.4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_267','Stegosaurus',9,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_268','Stenopelix',1.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_269','Struthiomimus',4,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_27','Aralosaurus',8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_270','Struthiosaurus',2.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_271','Styracosaurus',5.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_272','Suchomimus',11,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_273','Supersaurus',35,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_274','Talarurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_275','Tanius',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_276','Tarbosaurus',10,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_277','Tarchia',8.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_278','Telmatosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_279','Tenontosaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_28','Archaeoceratops',1.3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_280','Thecodontosaurus',2.5,'Omnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_281','Therizinosaurus',12,'Unknown','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_282','Thescelosaurus',3.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_283','Torosaurus',7.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_284','Torvosaurus',10,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_285','Triceratops',9,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_286','Troodon',2,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_287','Tsagantegia',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_288','Tsintaosaurus',12,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_289','Tuojiangosaurus',7,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_29','Archaeopteryx',0.5,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_290','Tylocephale',1.4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_291','Tyrannosaurus',12,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_292','Udanoceratops',4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_293','Unenlagia',2.4,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_294','Urbacodon',1,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_295','Utahraptor',6,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_296','Valdosaurus',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_297','Velociraptor',1.8,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_298','Vulcanodon',6.5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_299','Yandusaurus',3,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_30','Archaeornithomimus',3.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_300','Yangchuanosaurus',10,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_301','Yimenosaurus',9,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_302','Yingshanosaurus',4,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_303','Yinlong',1.2,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_304','Yuanmousaurus',17,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_305','Yunnanosaurus',7,'Omnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_306','Zalmoxes',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_307','Zephyrosaurus',1.8,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_308','Zuniceratops',3.5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_31','Argentinosaurus',35,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_32','Arrhinoceratops',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_33','Atlascopcosaurus',3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_34','Aucasaurus',5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_35','Austrosaurus',15,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_36','Avaceratops',2.3,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_37','Avimimus',1.5,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_38','Bactrosaurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_39','Bagaceratops',1,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_40','Bambiraptor',1,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_41','Barapasaurus',14,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_42','Barosaurus',24,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_43','Baryonyx',10,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_44','Becklespinax',5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_45','Beipiaosaurus',2,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_46','Bellusaurus',5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_47','Borogovia',1.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_48','Brachiosaurus',30,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_49','Brachylophosaurus',7,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_50','Brachytrachelopan',10,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_51','Buitreraptor',1.3,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_52','Camarasaurus',23,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_53','Camptosaurus',5,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_54','Carcharodontosaurus',15,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_55','Carnotaurus',7.6,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_56','Caudipteryx',1,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_57','Cedarpelta',10,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_58','Ceratosaurus',6,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_59','Cetiosauriscus',15,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_60','Cetiosaurus',18,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_61','Chaoyangsaurus',1.1,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_62','Chasmosaurus',5,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_63','Chindesaurus',4,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_64','Chinshakiangosaurus',11,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_65','Chirostenotes',1.7,'Omnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_66','Chubutisaurus',23,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_67','Chungkingosaurus',4,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_68','Citipati',2.1,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_69','Coelophysis',2,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_70','Coelurus',1.8,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_71','Coloradisaurus',4,'Omnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_72','Compsognathus',0.7,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_73','Conchoraptor',1.5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_74','Confuciusornis',0.3,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_75','Corythosaurus',10,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_76','Cryolophosaurus',8,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_77','Dacentrurus',6,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_78','Daspletosaurus',9,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_79','Datousaurus',15,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_80','Deinocheirus',10,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_81','Deinonychus',3,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_82','Deltadromeus',8.1,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_83','Dicraeosaurus',20,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_84','Dilophosaurus',6,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_85','Diplodocus',26,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_86','Dromaeosaurus',1.8,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_87','Dromiceiomimus',3.5,'Omnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_88','Dryosaurus',4,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_89','Dryptosaurus',6.4,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_90','Dubreuillosaurus',5,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_91','Edmontonia',4,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_92','Edmontosaurus',13,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_93','Einiosaurus',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_94','Elaphrosaurus',6.2,'Carnivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_95','Emausaurus',2,'Herbivorous','Jurassic');
INSERT INTO Dinosaur VALUES('DINO_96','Eolambia',6,'Herbivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_97','Eoraptor',1,'Carnivorous','Triassic');
INSERT INTO Dinosaur VALUES('DINO_98','Eotyrannus',5,'Carnivorous','Cretaceous');
INSERT INTO Dinosaur VALUES('DINO_99','Equijubus',7,'Herbivorous','Cretaceous');



INSERT INTO Fossil VALUES(1001,'South africa',2009,'Yates Bonnan Neveling Chinsamy and Blackbeard','DINO_285');
INSERT INTO Fossil VALUES(1002,'Argentina',1985,'Bonaparte and Novas','DINO_170');
INSERT INTO Fossil VALUES(1003,'USA',1995,'Sampson','DINO_99');
INSERT INTO Fossil VALUES(1004,'Mongolia',1999,'Perle Norell and Clark','DINO_188');
INSERT INTO Fossil VALUES(1005,'USA',1950,'Stovall and Langston','DINO_297');
INSERT INTO Fossil VALUES(1006,'Egypt',1932,'Stromer','DINO_47');
INSERT INTO Fossil VALUES(1007,'Niger',1944,'Sereno Wilson Larsson Dutheil and Sues','DINO_75');
INSERT INTO Fossil VALUES(1008,'China',1990,'Peng','DINO_76');
INSERT INTO Fossil VALUES(1009,'USA',1922,'Gilmore','DINO_301');
INSERT INTO Fossil VALUES(1010,'USA',2007,'Ryan','DINO_19');
INSERT INTO Fossil VALUES(1011,'Canada',1914,'Lamb','DINO_140');
INSERT INTO Fossil VALUES(1012,'Mongolia',1933,'Gilmore','DINO_74');
INSERT INTO Fossil VALUES(1013,'Mongolia',1976,'Kurzanov','DINO_207');
INSERT INTO Fossil VALUES(1014,'USA',1877,'Marsh','DINO_121');
INSERT INTO Fossil VALUES(1015,'Argentina',1991,'Bonaparte','DINO_31');
INSERT INTO Fossil VALUES(1016,'Argentina',1991,'Salgado and Bonaparte','DINO_181');
INSERT INTO Fossil VALUES(1017,'USA',1891,'Marsh','DINO_19');
INSERT INTO Fossil VALUES(1018,'France',1995,'Le Loeuff','DINO_72');
INSERT INTO Fossil VALUES(1019,'Argentina',1947,'Cabrera','DINO_216');
INSERT INTO Fossil VALUES(1020,'Canada',1914,'Brown','DINO_106');
INSERT INTO Fossil VALUES(1021,'USA',1885,'Marsh','DINO_261');
INSERT INTO Fossil VALUES(1022,'USA',1908,'Brown','DINO_142');
INSERT INTO Fossil VALUES(1023,'Mongolia',1988,'Barsbold','DINO_265');
INSERT INTO Fossil VALUES(1024,'Uruguay',1929,'Von Huene','DINO_30');
INSERT INTO Fossil VALUES(1025,'USA',1877,'Marsh','DINO_289');
INSERT INTO Fossil VALUES(1026,'Spain',1987,'Sanz Buscalioni Casanovas and Sanafa','DINO_41');
INSERT INTO Fossil VALUES(1027,'Kazakhstan',1968,'Rozhdestvensky','DINO_228');
INSERT INTO Fossil VALUES(1028,'China',1987,'Dong and Azuma','DINO_230');
INSERT INTO Fossil VALUES(1029,'Germany',1861,'Mayer','DINO_207');
INSERT INTO Fossil VALUES(1030,'Uzbekistan',1972,'Russell','DINO_87');
INSERT INTO Fossil VALUES(1031,'Argentina',1993,'Bonaparte and Coria','DINO_117');
INSERT INTO Fossil VALUES(1032,'Canada',1925,'Parks','DINO_305');
INSERT INTO Fossil VALUES(1033,'Australia',1989,'Rich and Rich','DINO_147');
INSERT INTO Fossil VALUES(1034,'Argentina',2002,'Coria Chiappe and Dingus','DINO_236');
INSERT INTO Fossil VALUES(1035,'Australia',1933,'Longman','DINO_10');
INSERT INTO Fossil VALUES(1036,'USA',1986,'Dodson','DINO_69');
INSERT INTO Fossil VALUES(1037,'Mongolia',1981,'Kurzanov','DINO_296');
INSERT INTO Fossil VALUES(1038,'China',1933,'Gilmore','DINO_274');
INSERT INTO Fossil VALUES(1039,'Mongolia',1975,'Maryanska and Osmolska','DINO_54');
INSERT INTO Fossil VALUES(1040,'USA',2000,'Burnham Derstler Currie Bakker Zhou and Ostrom','DINO_102');
INSERT INTO Fossil VALUES(1041,'India',1975,'Jain Kutty Roy-Chowdhury and Chatterjee','DINO_219');
INSERT INTO Fossil VALUES(1042,'USA',1890,'Marsh','DINO_198');
INSERT INTO Fossil VALUES(1043,'United kingdom',1987,'Charig and Milner','DINO_130');
INSERT INTO Fossil VALUES(1044,'United kingdom',1988,'Paul','DINO_200');
INSERT INTO Fossil VALUES(1045,'China',1999,'Xu Tang and Wang','DINO_191');
INSERT INTO Fossil VALUES(1046,'China',1990,'Dong and Azuma','DINO_201');
INSERT INTO Fossil VALUES(1047,'Mongolia',1987,'Osmalska','DINO_162');
INSERT INTO Fossil VALUES(1048,'USA',1903,'Riggs','DINO_287');
INSERT INTO Fossil VALUES(1049,'USA',1953,'C. M. Sternberg','DINO_36');
INSERT INTO Fossil VALUES(1050,'Argentina',2005,'Rauhut Remes Fechner Cladera and Puerta','DINO_209');
INSERT INTO Fossil VALUES(1051,'Argentina',2005,'Makovicky Apestegui  Agnolin','DINO_07');
INSERT INTO Fossil VALUES(1052,'USA',1877,'Cope','DINO_92');
INSERT INTO Fossil VALUES(1053,'USA',1885,'Marsh','DINO_138');
INSERT INTO Fossil VALUES(1054,'North africa',1931,'Stromer','DINO_185');
INSERT INTO Fossil VALUES(1055,'Argentina',1985,'Bonaparte','DINO_180');
INSERT INTO Fossil VALUES(1056,'China',1998,'Ji Currie Norell and Ji.','DINO_54');
INSERT INTO Fossil VALUES(1057,'USA',2001,'Carpenter Kirkland Burge and Bird','DINO_192');
INSERT INTO Fossil VALUES(1058,'USA',1884,'Marsh','DINO_256');
INSERT INTO Fossil VALUES(1059,'United kingdom',1927,'Von Huene','DINO_190');
INSERT INTO Fossil VALUES(1060,'United kingdom',1871,'Phillips','DINO_50');
INSERT INTO Fossil VALUES(1061,'China',1999,'Zhao Cheng and Xu','DINO_259');
INSERT INTO Fossil VALUES(1062,'Canada',1914,'Lawrence Lamb','DINO_160');
INSERT INTO Fossil VALUES(1063,'USA',1995,'Long and Murry','DINO_94');
INSERT INTO Fossil VALUES(1064,'China',1975,'Yeh','DINO_237');
INSERT INTO Fossil VALUES(1065,'Canada',1924,'Gilmore','DINO_172');
INSERT INTO Fossil VALUES(1066,'Argentina',1974,'Corro','DINO_144');
INSERT INTO Fossil VALUES(1067,'China',1983,'Dong Zhou and Zhang','DINO_189');
INSERT INTO Fossil VALUES(1068,'Mongolia',2001,'Clark Norell and Barsbold','DINO_296');
INSERT INTO Fossil VALUES(1069,'Zimbabwe',1989,'Edward Drinker Cope','DINO_34');
INSERT INTO Fossil VALUES(1070,'USA',1879,'Marsh','DINO_158');
INSERT INTO Fossil VALUES(1071,'Argentina',1978,'Bonaparte','DINO_258');
INSERT INTO Fossil VALUES(1072,'Germany',1859,'Wagner','DINO_153');
INSERT INTO Fossil VALUES(1073,'Mongolia',1986,'Barsbold','DINO_254');
INSERT INTO Fossil VALUES(1074,'China',1995,'Hou Zhou Gu and Zhang','DINO_96');
INSERT INTO Fossil VALUES(1075,'USA',1914,'Brown','DINO_130');
INSERT INTO Fossil VALUES(1076,'Antarctica',1994,'Hammer and Hickerson','DINO_172');
INSERT INTO Fossil VALUES(1077,'United kingdom',1902,'Lucas','DINO_240');
INSERT INTO Fossil VALUES(1078,'Canada',1970,'Russell','DINO_30');
INSERT INTO Fossil VALUES(1079,'China',1984,'Dong and Tang','DINO_216');
INSERT INTO Fossil VALUES(1080,'Mongolia',1970,'Osmalska and Roniewicz','DINO_180');
INSERT INTO Fossil VALUES(1081,'USA',1969,'Ostrom','DINO_250');
INSERT INTO Fossil VALUES(1082,'Morocco',1996,'Sereno Duthiel Iarochene Larsson Lyon Magwene Sidor Varricchio and Wilson','DINO_290');
INSERT INTO Fossil VALUES(1083,'Tanzania',1914,'Janensch','DINO_124');
INSERT INTO Fossil VALUES(1084,'USA',1942,'Samuel Welles','DINO_72');
INSERT INTO Fossil VALUES(1085,'USA',1878,'Marsh','DINO_242');
INSERT INTO Fossil VALUES(1086,'USA',1922,'Matthew and Brown','DINO_212');
INSERT INTO Fossil VALUES(1087,'Canada',1926,'Parks','DINO_52');
INSERT INTO Fossil VALUES(1088,'USA',1894,'Marsh','DINO_20');
INSERT INTO Fossil VALUES(1089,'USA',1866,'Cope','DINO_214');
INSERT INTO Fossil VALUES(1090,'France',2005,'Allain','DINO_124');
INSERT INTO Fossil VALUES(1091,'Canada',1928,'Sternberg','DINO_137');
INSERT INTO Fossil VALUES(1092,'Canada',1917,'Lambe','DINO_76');
INSERT INTO Fossil VALUES(1093,'USA',1995,'Sampson','DINO_191');
INSERT INTO Fossil VALUES(1094,'Tanzania',1920,'Janensch','DINO_83');
INSERT INTO Fossil VALUES(1095,'Germany',1991,'Haubold','DINO_102');
INSERT INTO Fossil VALUES(1096,'USA',1998,'Kirkland','DINO_02');
INSERT INTO Fossil VALUES(1097,'Argentina',1993,'Sereno Forster Rogers and Monetta','DINO_255');
INSERT INTO Fossil VALUES(1098,'United kingdom',2001,'Hutt Naish Martill Barker and Newberry','DINO_308');
INSERT INTO Fossil VALUES(1099,'China',2003,'You Luo Shubin Witmer Tang and Tang','DINO_118');
INSERT INTO Fossil VALUES(1100,'Mongolia',2006,'Ksepka and Norell','DINO_288');
INSERT INTO Fossil VALUES(1101,'Mongolia',1980,'Perle Vide Barsbold and Perle','DINO_127');
INSERT INTO Fossil VALUES(1102,'China',1929,'Wiman','DINO_125');
INSERT INTO Fossil VALUES(1103,'USA',1964,'Oscar Kuhn','DINO_144');
INSERT INTO Fossil VALUES(1104,'Germany',2006,'Sander Mateus Laven and Knatschke','DINO_240');
INSERT INTO Fossil VALUES(1105,'United kingdom',1964,'Walker','DINO_136');
INSERT INTO Fossil VALUES(1106,'Japan',2000,'Azuma and Currie','DINO_295');
INSERT INTO Fossil VALUES(1107,'Japan',2003,'Kobayashi and Azuma','DINO_79');
INSERT INTO Fossil VALUES(1108,'Mongolia',1972,'Osmalska Roniewicz and Barsbold','DINO_270');
INSERT INTO Fossil VALUES(1109,'USA',1998,'Carpenter Miles and Cloward','DINO_101');
INSERT INTO Fossil VALUES(1110,'Mongolia',1981,'Barsbold','DINO_90');
INSERT INTO Fossil VALUES(1111,'China',1985,'Dong and Tang','DINO_29');
INSERT INTO Fossil VALUES(1112,'Argentina',1996,'Coria and Salgado','DINO_291');
INSERT INTO Fossil VALUES(1113,'USA',1998,'Kirkland','DINO_127');
INSERT INTO Fossil VALUES(1114,'Argentina',1995,'Coria and Salgado','DINO_101');
INSERT INTO Fossil VALUES(1115,'China',1979,'Brett-Surman','DINO_68');
INSERT INTO Fossil VALUES(1116,'Tanzania',1914,'Janensch','DINO_294');
INSERT INTO Fossil VALUES(1117,'China',2001,'Vickaryous Russell Currie and Zhao','DINO_308');
INSERT INTO Fossil VALUES(1118,'USA',1914,'Lamb','DINO_169');
INSERT INTO Fossil VALUES(1119,'Mongolia',1982,'Perle Maryaska and Osmalska','DINO_186');
INSERT INTO Fossil VALUES(1120,'Mongolia',2000,'Sereno','DINO_178');
INSERT INTO Fossil VALUES(1121,'USA',1914,'Lambe','DINO_246');
INSERT INTO Fossil VALUES(1122,'Brazil',1999,'Bonaparte Ferigolo and Ribeiro','DINO_48');
INSERT INTO Fossil VALUES(1123,'China',2006,'Xu Clark Forster Norell Erickson Eberth Jia and Zhao','DINO_15');
INSERT INTO Fossil VALUES(1124,'USA',1858,'Leidy','DINO_96');
INSERT INTO Fossil VALUES(1125,'USA',2005,'Zanno and Sampson','DINO_69');
INSERT INTO Fossil VALUES(1126,'USA',1903,'Hatcher','DINO_264');
INSERT INTO Fossil VALUES(1127,'Mongolia',1984,'Barsbold and Perle','DINO_149');
INSERT INTO Fossil VALUES(1128,'Argentina',1963,'Reig','DINO_206');
INSERT INTO Fossil VALUES(1129,'USA',2001,'Carpenter Miles and Cloward','DINO_295');
INSERT INTO Fossil VALUES(1130,'South africa',1962,'Crompton and Charig','DINO_152');
INSERT INTO Fossil VALUES(1131,'Mongolia',1981,'Barsbold','DINO_157');
INSERT INTO Fossil VALUES(1132,'Mongolia',1974,'Maryaka and Osmalska','DINO_270');
INSERT INTO Fossil VALUES(1133,'China',1982,'Dong Tang and Zhou','DINO_04');
INSERT INTO Fossil VALUES(1134,'United kingdom',1833,'Mantell','DINO_99');
INSERT INTO Fossil VALUES(1135,'USA',1913,'Brown','DINO_140');
INSERT INTO Fossil VALUES(1136,'United kingdom',1869,'Huxley','DINO_265');
INSERT INTO Fossil VALUES(1137,'United kingdom',1881,'Boulenger and Van Beneden','DINO_300');
INSERT INTO Fossil VALUES(1138,'India',1933,'Huene and Matley','DINO_287');
INSERT INTO Fossil VALUES(1139,'Brazil',1996,'Martill Cruickshank Frey Small and Clarke','DINO_100');
INSERT INTO Fossil VALUES(1140,'India',1997,'Jain and Bandyopadhyay','DINO_281');
INSERT INTO Fossil VALUES(1141,'Tanzania',1991,'Wild','DINO_209');
INSERT INTO Fossil VALUES(1142,'Kazakhstan',1939,'Riabinin','DINO_216');
INSERT INTO Fossil VALUES(1143,'China',1995,'Zhang and Yang','DINO_220');
INSERT INTO Fossil VALUES(1144,'China',2001,'Wang and Xu','DINO_244');
INSERT INTO Fossil VALUES(1145,'Niger',1999,'Sereno Beck Dutheil Larsson Lyon Moussa Sadleir Sidor Varricchio Wilson and Wilson','DINO_283');
INSERT INTO Fossil VALUES(1146,'Germany',2006,'Ursula Gohlich and Luis Chiappe','DINO_262');
INSERT INTO Fossil VALUES(1147,'Tanzania',1915,'Hennig','DINO_246');
INSERT INTO Fossil VALUES(1148,'Mongolia',2001,'Clark Norell and Barsbold','DINO_62');
INSERT INTO Fossil VALUES(1149,'India',1988,'Yadagiri','DINO_232');
INSERT INTO Fossil VALUES(1150,'USA',1910,'Brown','DINO_180');
INSERT INTO Fossil VALUES(1151,'Canada',1923,'Parks','DINO_297');
INSERT INTO Fossil VALUES(1152,'Madagascar',1986,'Bonaparte','DINO_183');
INSERT INTO Fossil VALUES(1153,'Australia',1989,'Rich and Rich','DINO_09');
INSERT INTO Fossil VALUES(1154,'USA',1914,'Brown','DINO_35');
INSERT INTO Fossil VALUES(1155,'Lesotho',1978,'Galton','DINO_75');
INSERT INTO Fossil VALUES(1156,'China',2002,'Xu Makovicky Wang Norell and You','DINO_222');
INSERT INTO Fossil VALUES(1157,'Argentina',2006,'Bonaparte Gonza¡Lez Riga and Apestegua','DINO_290');
INSERT INTO Fossil VALUES(1158,'Germany',1934,'Huene','DINO_128');
INSERT INTO Fossil VALUES(1159,'USA',1960,'Xu Makovicky Wang Norell and You','DINO_138');
INSERT INTO Fossil VALUES(1160,'France',1993,'Ezcurra and Cuny 2007','DINO_289');
INSERT INTO Fossil VALUES(1161,'China',1941,'Young','DINO_16');
INSERT INTO Fossil VALUES(1162,'Niger',1999,'Taquet  Russell','DINO_246');
INSERT INTO Fossil VALUES(1163,'South africa',1924,'Haughton','DINO_154');
INSERT INTO Fossil VALUES(1164,'Romania',1915,'Nopcsa','DINO_243');
INSERT INTO Fossil VALUES(1165,'USA',1979,'Horner and Makela','DINO_201');
INSERT INTO Fossil VALUES(1166,'Madagascar',1979,'Sues  Taquet','DINO_273');
INSERT INTO Fossil VALUES(1167,'Malawi',1928,'Haughton','DINO_169');
INSERT INTO Fossil VALUES(1168,'China',1954,'Young','DINO_114');
INSERT INTO Fossil VALUES(1169,'Argentina',2006,'Coria and Currie','DINO_174');
INSERT INTO Fossil VALUES(1170,'USA',1976,'Madsen','DINO_290');
INSERT INTO Fossil VALUES(1171,'Madagascar',2001,'Sampson Carrano  Forster','DINO_95');
INSERT INTO Fossil VALUES(1172,'Zimbabwe',1854,'Owen','DINO_78');
INSERT INTO Fossil VALUES(1173,'Brazil',2006,'Kellner Et Al.','DINO_169');
INSERT INTO Fossil VALUES(1174,'United kingdom',1826,'Ritgen','DINO_248');
INSERT INTO Fossil VALUES(1175,'South africa',1924,'Haughton','DINO_241');
INSERT INTO Fossil VALUES(1176,'United kingdom',1964,'Walker','DINO_225');
INSERT INTO Fossil VALUES(1177,'Mongolia',1953,'Bohlin','DINO_48');
INSERT INTO Fossil VALUES(1178,'China',1978,'Dong','DINO_76');
INSERT INTO Fossil VALUES(1179,'China',2000,'Xu Zhou and Wang','DINO_73');
INSERT INTO Fossil VALUES(1180,'Australia',1980,'Molnar','DINO_173');
INSERT INTO Fossil VALUES(1181,'China',1993,'Zhao and Currie','DINO_108');
INSERT INTO Fossil VALUES(1182,'Mongolia',1993,'Perle Norell Chiappe and Clark','DINO_69');
INSERT INTO Fossil VALUES(1183,'Argentina',1979,'Bonaparte and Vince','DINO_260');
INSERT INTO Fossil VALUES(1184,'Australia',1981,'Bartholomai and Molnar','DINO_43');
INSERT INTO Fossil VALUES(1185,'China',1979,'Dong','DINO_115');
INSERT INTO Fossil VALUES(1186,'USA',1905,'Lull','DINO_111');
INSERT INTO Fossil VALUES(1187,'Mongolia',1971,'Nowinski','DINO_202');
INSERT INTO Fossil VALUES(1188,'United kingdom',1996,'Hutt Martill and Barker','DINO_07');
INSERT INTO Fossil VALUES(1189,'Argentina',1893,'Lydekker','DINO_224');
INSERT INTO Fossil VALUES(1190,'Tunisia',1999,'Sereno Beck Dutheil Larsson Lyon Moussa Sadleir Sidor Varricchio Wilson &Amp  Wilson','DINO_258');
INSERT INTO Fossil VALUES(1191,'Russia',1936,'Nagao','DINO_43');
INSERT INTO Fossil VALUES(1192,'Argentina',1980,'Bonaparte and Powell','DINO_148');
INSERT INTO Fossil VALUES(1193,'USA',1889,'Marsh','DINO_206');
INSERT INTO Fossil VALUES(1194,'Mongolia',2000,'Barsbold Osmalska Watabe Currie and Tsogtbaatar','DINO_155');
INSERT INTO Fossil VALUES(1195,'USA',2001,'Kirkland and Wolfe','DINO_10');
INSERT INTO Fossil VALUES(1196,'South africa',2000,'De Klerk Forster Sampson Chinsamy and Ross','DINO_76');
INSERT INTO Fossil VALUES(1197,'China',1939,'Young','DINO_255');
INSERT INTO Fossil VALUES(1198,'Mongolia',1977,'Borsuk-Bialynicka','DINO_253');
INSERT INTO Fossil VALUES(1199,'USA',1933,'Osbourne','DINO_111');
INSERT INTO Fossil VALUES(1200,'USA',1890,'Marsh','DINO_273');
INSERT INTO Fossil VALUES(1201,'USA',1988,'Horner and Weishampel','DINO_59');
INSERT INTO Fossil VALUES(1202,'USA',2007,'Varricchio Marin and Katsura','DINO_246');
INSERT INTO Fossil VALUES(1203,'USA',1877,'Marsh','DINO_223');
INSERT INTO Fossil VALUES(1204,'Niger',1976,'Taquet','DINO_233');
INSERT INTO Fossil VALUES(1205,'Mongolia',1924,'Osborn','DINO_55');
INSERT INTO Fossil VALUES(1206,'USA',1943,'Brown and Schlaikjer','DINO_146');
INSERT INTO Fossil VALUES(1207,'Canada',1950,'Sternberg','DINO_95');
INSERT INTO Fossil VALUES(1208,'USA',1919,'Lambe','DINO_197');
INSERT INTO Fossil VALUES(1209,'Wales',2003,'Galton Yates and Kermack','DINO_64');
INSERT INTO Fossil VALUES(1210,'Egypt',2001,'Smith Lamanna Lacovara Dodson Smith Poole Giegengack and Attia','DINO_164');
INSERT INTO Fossil VALUES(1211,'USA',1922,'Parks','DINO_53');
INSERT INTO Fossil VALUES(1212,'Canada',1937,'Sternberg','DINO_212');
INSERT INTO Fossil VALUES(1213,'Argentina',1979,'Bonaparte','DINO_244');
INSERT INTO Fossil VALUES(1214,'Spain',1994,'Parez-Moreno Sanz Buscalioni Moratalla Ortega and Rasskin-Gutman','DINO_234');
INSERT INTO Fossil VALUES(1215,'United kingdom',1850,'Mantell','DINO_239');
INSERT INTO Fossil VALUES(1216,'USA',1923,'Osborn','DINO_200');
INSERT INTO Fossil VALUES(1217,'Argentina',1979,'Bonaparte','DINO_96');
INSERT INTO Fossil VALUES(1218,'Mongolia',1933,'Gilmore','DINO_276');
INSERT INTO Fossil VALUES(1219,'Switzerland',1837,'Meyer','DINO_26');
INSERT INTO Fossil VALUES(1220,'USA',1911,'Talbot','DINO_09');
INSERT INTO Fossil VALUES(1221,'France',1838,'Eudes-Deslongchamps','DINO_42');
INSERT INTO Fossil VALUES(1222,'United kingdom',1881,'Hulke','DINO_67');
INSERT INTO Fossil VALUES(1223,'Mongolia',1974,'Maryaska and Osmlska','DINO_286');
INSERT INTO Fossil VALUES(1224,'China',1966,'Rozhdestvensky','DINO_162');
INSERT INTO Fossil VALUES(1225,'United kingdom',1910,'Woodward','DINO_89');
INSERT INTO Fossil VALUES(1226,'Germany',1913,'Fraas','DINO_153');
INSERT INTO Fossil VALUES(1227,'USA',1916,'Brown','DINO_119');
INSERT INTO Fossil VALUES(1228,'China',1997,'Ji and Ji','DINO_77');
INSERT INTO Fossil VALUES(1229,'Mongolia',1923,'Granger and Gregory','DINO_177');
INSERT INTO Fossil VALUES(1230,'USA',1998,'Head','DINO_176');
INSERT INTO Fossil VALUES(1231,'Russia',1923,'Osborn','DINO_58');
INSERT INTO Fossil VALUES(1232,'Mongolia',1983,'Kurzanov and Bannikov','DINO_194');
INSERT INTO Fossil VALUES(1233,'Morocco',1954,'Lavocat','DINO_218');
INSERT INTO Fossil VALUES(1234,'Spain',1869,'Matherton','DINO_222');
INSERT INTO Fossil VALUES(1235,'Australia',1926,'Longman','DINO_92');
INSERT INTO Fossil VALUES(1236,'Mongolia',1986,'Barsbold','DINO_58');
INSERT INTO Fossil VALUES(1237,'Argentina',1969,'Bonaparte','DINO_287');
INSERT INTO Fossil VALUES(1238,'Niger',2004,'Sereno Wilson and Conrad','DINO_202');
INSERT INTO Fossil VALUES(1239,'Mongolia',1977,'Maryaska','DINO_43');
INSERT INTO Fossil VALUES(1240,'Argentina',1980,'Bonaparte and Powell','DINO_259');
INSERT INTO Fossil VALUES(1241,'United kingdom',1910,'Huene','DINO_71');
INSERT INTO Fossil VALUES(1242,'United kingdom',1921,'andrews','DINO_160');
INSERT INTO Fossil VALUES(1243,'Mongolia',1912,'Brown','DINO_47');
INSERT INTO Fossil VALUES(1244,'USA',1970,'Ostrom','DINO_279');
INSERT INTO Fossil VALUES(1245,'USA',1996,'Chure','DINO_107');
INSERT INTO Fossil VALUES(1246,'Mongolia',1924,'Osborn','DINO_82');
INSERT INTO Fossil VALUES(1247,'United kingdom',1868,'Owen','DINO_265');
INSERT INTO Fossil VALUES(1248,'USA',1981,'Colbert','DINO_232');
INSERT INTO Fossil VALUES(1249,'Argentina',1979,'Brett-Surman','DINO_234');
INSERT INTO Fossil VALUES(1250,'USA',1936,'Camp','DINO_144');
INSERT INTO Fossil VALUES(1251,'Mongolia',1979,'Perle','DINO_09');
INSERT INTO Fossil VALUES(1252,'Mongolia',1983,'Tumanova','DINO_42');
INSERT INTO Fossil VALUES(1253,'Mongolia',2007,'Turner Hwang and Norell','DINO_97');
INSERT INTO Fossil VALUES(1254,'China',1973,'Hu','DINO_236');
INSERT INTO Fossil VALUES(1255,'China',1983,'Dong Zhou and Zhang','DINO_81');
INSERT INTO Fossil VALUES(1256,'Mongolia',1998,'Chiappe Norell and Clark','DINO_170');
INSERT INTO Fossil VALUES(1257,'USA',1960,'Eaton','DINO_94');
INSERT INTO Fossil VALUES(1258,'China',2007,'Ji Ji La and Yuan','DINO_299');
INSERT INTO Fossil VALUES(1259,'China',1999,'Xu Wang and Wu','DINO_151');
INSERT INTO Fossil VALUES(1260,'China',1996,'Ji and Ji','DINO_209');
INSERT INTO Fossil VALUES(1261,'China',2002,'Xu Norell Wang Makovicky and Wu','DINO_265');
INSERT INTO Fossil VALUES(1262,'China',1992,'Gao','DINO_94');
INSERT INTO Fossil VALUES(1263,'China',2006,'Xu Zhang Tan Zhao and Tan','DINO_214');
INSERT INTO Fossil VALUES(1264,'Morocco',1915,'Stromer','DINO_208');
INSERT INTO Fossil VALUES(1265,'Brazil',1970,'Colbert','DINO_239');
INSERT INTO Fossil VALUES(1266,'USA',1902,'Lambe','DINO_11');
INSERT INTO Fossil VALUES(1267,'USA',1877,'Marsh','DINO_278');
INSERT INTO Fossil VALUES(1268,'Germany',1857,'Meyer','DINO_106');
INSERT INTO Fossil VALUES(1269,'Canada',1917,'Osborn','DINO_218');
INSERT INTO Fossil VALUES(1270,'Spain',1871,'Bunzel','DINO_04');
INSERT INTO Fossil VALUES(1271,'USA',1913,'Lambe','DINO_86');
INSERT INTO Fossil VALUES(1272,'Niger',1998,'Sereno Beck Dutheil Gado Larsson Lyon Marcot Rauhut Sadleir Sidor Varricchio Wilson and Wilson','DINO_24');
INSERT INTO Fossil VALUES(1273,'USA',1985,'Jansen','DINO_262');
INSERT INTO Fossil VALUES(1274,'Mongolia',1952,'Maleev','DINO_59');
INSERT INTO Fossil VALUES(1275,'China',1929,'Wiman','DINO_129');
INSERT INTO Fossil VALUES(1276,'Mongolia',1955,'Maleev','DINO_229');
INSERT INTO Fossil VALUES(1277,'Mongolia',1956,'Maleev','DINO_139');
INSERT INTO Fossil VALUES(1278,'Spain',1900,'Nopcsa','DINO_45');
INSERT INTO Fossil VALUES(1279,'USA',1970,'Ostrom','DINO_148');
INSERT INTO Fossil VALUES(1280,'United kingdom',1843,'Morris','DINO_80');
INSERT INTO Fossil VALUES(1281,'Mongolia',1915,'Maleev','DINO_243');
INSERT INTO Fossil VALUES(1282,'USA',1913,'Gilmore','DINO_250');
INSERT INTO Fossil VALUES(1283,'USA',1891,'Marsh','DINO_143');
INSERT INTO Fossil VALUES(1284,'USA',1979,'Galton and Jensen','DINO_165');
INSERT INTO Fossil VALUES(1285,'USA',1889,'Marsh','DINO_40');
INSERT INTO Fossil VALUES(1286,'USA',1856,'Leidy','DINO_217');
INSERT INTO Fossil VALUES(1287,'Mongolia',1993,'Tumanova','DINO_223');
INSERT INTO Fossil VALUES(1288,'China',1958,'Young','DINO_185');
INSERT INTO Fossil VALUES(1289,'China',1973,'Dong Li Zhou and Zhang','DINO_18');
INSERT INTO Fossil VALUES(1290,'Mongolia',1974,'Maryaska and Osmlska','DINO_209');
INSERT INTO Fossil VALUES(1291,'USA',1905,'Osborn','DINO_135');
INSERT INTO Fossil VALUES(1292,'Mongolia',1992,'Kurzanov','DINO_285');
INSERT INTO Fossil VALUES(1293,'Argentina',1997,'Novas and Puerta','DINO_128');
INSERT INTO Fossil VALUES(1294,'Uzbekistan',2007,'Averianov and Sues','DINO_49');
INSERT INTO Fossil VALUES(1295,'USA',1993,'Kirkland Gaston and Burge','DINO_33');
INSERT INTO Fossil VALUES(1296,'United kingdom',1975,'Galton','DINO_171');
INSERT INTO Fossil VALUES(1297,'Mongolia',1924,'Osborn','DINO_135');
INSERT INTO Fossil VALUES(1298,'Zimbabwe',1972,'Raath','DINO_194');
INSERT INTO Fossil VALUES(1299,'China',1979,'He','DINO_209');
INSERT INTO Fossil VALUES(1300,'China',1978,'Dong Chang Li and Zhou','DINO_202');
INSERT INTO Fossil VALUES(1301,'China',1990,'Bai Yang and Wang','DINO_67');
INSERT INTO Fossil VALUES(1302,'China',1992,'Watanabe','DINO_259');
INSERT INTO Fossil VALUES(1303,'China',2006,'Xu Forster Clark and Mo','DINO_111');
INSERT INTO Fossil VALUES(1304,'China',2006,'La Li Ji Wang Zhang and Dong','DINO_122');
INSERT INTO Fossil VALUES(1305,'China',1942,'Young','DINO_192');
INSERT INTO Fossil VALUES(1306,'Romania',1902,'Nopcsa','DINO_91');
INSERT INTO Fossil VALUES(1307,'USA',1980,'Sues','DINO_222');
INSERT INTO Fossil VALUES(1308,'USA',1998,'Wolfe and Kirkland','DINO_163');
